<?xml version="1.0"?>
<package format="2">

  <name>image_preprocessing</name>
  <version>1.0.2</version>
  <description>The image_preprocessing package</description>

  <url type="website">http://wiki.ros.org/image_preprocessing</url>

  <maintainer email="bo-miquel.nordfeldt@uib.eu">Bo Miquel Nordfeldt-Fiol</maintainer>
  <author email="miquel.massot@uib.cat">Miquel Massot</author>

  <license>BSD</license>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- ROS Dependencies (Build + Exec) -->
  <depend>roscpp</depend>
  <depend>pcl_ros</depend>
  <depend>cv_bridge</depend>
  <depend>sensor_msgs</depend>
  <depend>stereo_msgs</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>message_filters</depend>
  <depend>stereo_image_proc</depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
  </export>

</package>