slamon:
  enable_bucketing: false
  enable_debugging: true
  enable_enhacement: true
  feature_detector_name: sift
  lc_candidates: 3
  lc_discard_window: 20
  lc_neighbors: 3
  matching_type: circular_ratio_matching
  max_kpts_bucket: 3
  max_kpts_retained: 1500
  min_inliers: 40
  min_lc_inliers: 80
  motion_estimation_type: epnp
  robot_frame_id: girona500/base_link
  working_path: /home/bomiquel/Documents/recerca/slam/single_slam/data/slamon/uji/raw/naive/2024_07_04/experiment_0_square_2_v2/circular_ratio_matching/epnp/execution_9
